---
pipeline:

  prepare_npm_auth:
    image: node:9.9.0
    commands:
      - npm install npm-login-cmd --no-save
    secrets: [NPM_USER, NPM_PASS, NPM_EMAIL]
    environment:
      NPM_USER: [NPM_USER]
      NPM_PASS:
        from_secret: NPM_PASS
      NPM_EMAIL:
        from_secret: NPM_EMAIL
    when:
      event: [push, tag]

  npm_auth:
    image: node:9.9.0
    commands:
      - npx npm-login-cmd

  install:
    image: node:9.9.0
    commands:
      - npm install
      - npm run init
    when:
      event: [push, tag]
      status: [success]

  build:
    image: node:9.9.0
    commands:
      - npm run build --prod
    when:
      event: [push, tag]
      status: [success]

  build-docker-image:
    image: plugins/docker
    insecure: true
    registry: registry.tola.io
    repo: registry.tola.io/humanitec/walhall-sample-angular-app
    file: Dockerfile
    auto_tag: true
    secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
    when:
      event: [tag]
      status: [success]

  notify:
    image: plugins/slack
    channel: drone-ci
    username: Drone-CI
    secrets: [SLACK_WEBHOOK]
    when:
      status: [failure]
