---
pipeline:

  install:
    image: node:9.9.0
    commands:
      - npm install npm-login-cmd -g
      - npm install gulp-cli -g
      - npm config set registry https://npm-proxy.fury.io/$${NPM_TOKEN}/humanitec/
      - npm config set always-auth
      - npx npm-login-cmd
      - npm install
      - npm run init
    secrets: [NPM_USER, NPM_PASS, NPM_EMAIL, NPM_TOKEN]
    when:
      event: [push, tag]

  build:
    image: node:9.9.0
    commands:
      - npm run build-prod
    when:
      event: [push, tag]
      status: [success]

#  test:
#    image: registry.tola.io/humanitec/docker-nodejs-and-chrome:0.0.1-8.12.0-latest
#    commands:
#      - npm rebuild node-sass
#      - npm run test
#    when:
#      event: [push]
#      status: [success]

  build-docker-image-tag:
    image: plugins/docker
    registry:
      from_secret: DOCKER_REGISTRY
    repo:
      from_secret: DOCKER_REPO
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    auto_tag: true
    insecure: true
    file: Dockerfile
    when:
      event: [tag]
      status: [success]

  notify:
    image: plugins/slack
    channel: drone-ci
    username: Drone-CI
    secrets: [SLACK_WEBHOOK]
    when:
      status: [failure]
